# Input files
genome: "/home/centos/GenePanelVariantCallingSmk/resources/genome/GRCh38.primary_assembly.genome.fa.gz"
annotation: "/home/centos/GenePanelVariantCallingSmk/resources/genome/gencode.v43.annotation.gtf.gz"
fastq_dir: "/home/centos/GenePanelVariantCallingSmk/fastq/"

samples:
  - sample_name: SRR10611150
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611150.fastq.gz
  - sample_name: SRR10611151
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611151.fastq.gz
  - sample_name: SRR10611152
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611152.fastq.gz
  - sample_name: SRR10611153
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611153.fastq.gz
  - sample_name: SRR10611154
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611154.fastq.gz
  - sample_name: SRR10611155
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611155.fastq.gz
  - sample_name: SRR10611156
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611156.fastq.gz
  - sample_name: SRR10611157
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611157.fastq.gz
  - sample_name: SRR10611177
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611177.fastq.gz
  - sample_name: SRR10611178
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611178.fastq.gz
  - sample_name: SRR10611179
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611179.fastq.gz
  - sample_name: SRR10611180
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611180.fastq.gz
  - sample_name: SRR10611181
    fastq_files: /home/centos/GenePanelVariantCallingSmk/fastq/SRR10611181.fastq.gz



# Computational resource
threads: 16
